package il.transit.core.search

import il.transit.core.api.GeocodeMatch
import il.transit.core.geo.Geo
import il.transit.core.geo.LatLon

/** A town: every spelling people type (Hebrew and English), its centre (OSM), how far it reaches. */
data class Town(val names: List<String>, val lat: Double, val lon: Double, val radiusKm: Double) {
    val centre: LatLon get() = LatLon(lat, lon)
    val name: String get() = names.first()

    fun contains(p: LatLon): Boolean = Geo.distanceM(centre, p) <= radiusKm * 1000
}

/**
 * The bundled town table (`TownsData`, generated by `tools/gen_towns.py`): which town a search
 * names, and whether an answer lies in it, in either language ("Ra'anana" answers a Hebrew
 * "רעננה"). 0 requests.
 */
object Towns {
    val ALL: List<Town> get() = TownsData.ALL

    private val byName: Map<String, Town> by lazy {
        ALL.flatMap { t -> t.names.map { PlaceSearch.normalize(it) to t } }.toMap()
    }
    private val longest: Int by lazy { byName.keys.maxOf { it.split(' ').size } }

    /** Words before a town name that make it a street ("דרך חברון", "שדרות ירושלים", "רחוב חיפה"). */
    private val STREET_WORDS = setOf("רחוב", "רח", "שדרות", "שד", "שדרת", "דרך", "כביש", "סמטת", "סמטה", "כיכר", "ככר", "מעלה", "st", "street", "rd", "road")

    fun named(name: String): Town? = byName[PlaceSearch.normalize(name)]

    /**
     * The town [query] names: its last words ("טבנקין 15 רעננה", "Herzl St 12, Haifa"), or its
     * first words when a comma follows them ("רעננה, טבנקין 15"); never a name that comes right
     * after a street word ("שדרות ירושלים"), and never a town name followed only by a number
     * ("ירושלים 5" is a street). Empty when none.
     */
    fun typedIn(query: String): List<Town> {
        val parts = query.split(',').map { words(it) }.filter { it.isNotEmpty() }
        if (parts.isEmpty()) return emptyList()
        val all = parts.flatten()
        val tail = all.dropLastWhile(::isHouseNumber)
        val numberAfter = tail.size < all.size
        suffix(tail)?.let { (town, start) ->
            val before = tail.getOrNull(start - 1)
            val alone = start == 0
            if (before !in STREET_WORDS && !(alone && numberAfter)) return listOf(town)
        }
        // "רעננה, טבנקין 15": a town alone before the first comma.
        if (parts.size > 1) named(parts.first().joinToString(" "))?.let { return listOf(it) }
        return emptyList()
    }

    /**
     * Whether [m] lies in [town]: by the town its answer names when the table knows that town
     * (so a street near the border is not counted in the next town), else by distance.
     */
    fun holds(town: Town, m: GeocodeMatch): Boolean {
        val named = PlaceSearch.townOf(m)?.let { byName[it] }
        return if (named != null) named == town else town.contains(LatLon(m.lat, m.lon))
    }

    private fun words(s: String) = PlaceSearch.normalize(QueryText.expand(s)).split(' ').filter { it.isNotEmpty() }

    private fun suffix(ws: List<String>): Pair<Town, Int>? {
        for (k in minOf(longest, ws.size) downTo 1) {
            val start = ws.size - k
            byName[ws.subList(start, ws.size).joinToString(" ")]?.let { return it to start }
        }
        return null
    }

    private fun isHouseNumber(w: String) = w.firstOrNull()?.isDigit() == true && w.length <= 5
}

/**
 * What the user typed, as the geocoders read it best: town abbreviations written with
 * gershayim spelled out (ת"א → תל אביב, ב"ש → באר שבע), "שד'" → שדרות, and "רחוב"/"רח'" dropped
 * (street names are indexed without it). Everything else is left as typed.
 */
object QueryText {
    private val TOWN_ABBREVIATIONS = mapOf(
        "תא" to "תל אביב", "בש" to "באר שבע", "פת" to "פתח תקווה", "רג" to "רמת גן",
        "ראשלצ" to "ראשון לציון", "רשלצ" to "ראשון לציון", "כס" to "כפר סבא", "קש" to "קריית שמונה",
        "קג" to "קריית גת", "ים" to "ירושלים", "י ם" to "ירושלים",
    )
    private val STREET = setOf("רחוב", "רח", "רח׳", "רח'")
    private val BOULEVARD = setOf("שד'", "שד׳", "שד")

    fun expand(text: String): String {
        val tokens = text.trim().split(Regex("\\s+")).filter { it.isNotEmpty() }
        val out = tokens.mapNotNull { raw ->
            val token = raw.trimEnd(',', '.')
            val comma = if (raw.endsWith(",")) "," else ""
            val bare = token.filterNot { it in "\"'״׳" }.replace('-', ' ')
            when {
                // Only with gershayim (ת"א, י-ם): a bare "תא" or "ים" is a word, not a town.
                token.any { it in "\"״" } || token == "י-ם" -> TOWN_ABBREVIATIONS[bare]?.plus(comma) ?: raw
                token in STREET && tokens.size > 1 -> comma.ifEmpty { null }
                token in BOULEVARD -> "שדרות$comma"
                else -> raw
            }
        }
        return out.joinToString(" ").trim().trimStart(',').trim()
    }
}
