#!/usr/bin/env python
"""Generate the bundled town table (names, centre, radius) for place search.

    python tools/gen_towns.py

Reads tools/towns_seed.tsv and asks Photon (photon.komoot.io, OSM) once per town for its
`place` point, sending the project User-Agent; writes
core/src/main/kotlin/il/transit/core/search/TownsData.kt. Used to tell which town a search
names ("טבנקין 15 רעננה") and whether an answer lies in it, in either language. One request
per town, one second apart: this is for re-generating the table, not for load.
"""
from __future__ import annotations

import json
import pathlib
import sys
import time
import urllib.parse
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
SEED = ROOT / "tools/towns_seed.tsv"
OUT = ROOT / "core/src/main/kotlin/il/transit/core/search/TownsData.kt"
UA = "IsraelTransitPlanner/0.1 (+https://github.com/EitanPinczowski/israel-transit-planner)"
BBOX = "34.2,29.45,35.95,33.35"


def centre(name: str) -> tuple[float, float] | None:
    q = urllib.parse.urlencode({"q": name, "lang": "default", "osm_tag": "place", "bbox": BBOX, "limit": 5})
    req = urllib.request.Request(f"https://photon.komoot.io/api?{q}", headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        feats = json.load(r)["features"]
    for kind in (("city", "town"), ("village", "hamlet", "suburb", "neighbourhood", "isolated_dwelling", "locality")):
        for f in feats:
            if f["properties"].get("osm_value") in kind:
                lon, lat = f["geometry"]["coordinates"]
                return round(lat, 5), round(lon, 5)
    return None


def kt(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    rows, missing = [], []
    for line in SEED.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        he, en, radius = line.split("\t")
        names = he.split("|") + en.split("|")
        at = centre(names[0])
        time.sleep(1)
        if at is None:
            missing.append(names[0])
            continue
        rows.append(f"        Town(listOf({', '.join(kt(n) for n in names)}), {at[0]}, {at[1]}, {float(radius)}),")
    OUT.write_text(
        "package il.transit.core.search\n\n"
        "// GENERATED by tools/gen_towns.py from tools/towns_seed.tsv and Photon (OSM) — do not edit by hand.\n"
        f"// {len(rows)} towns.\n"
        "internal object TownsData {\n    val ALL: List<Town> = listOf(\n" + "\n".join(rows) + "\n    )\n}\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} towns")
    if missing:
        print("not found on Photon:", ", ".join(missing), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
