#!/usr/bin/env python
"""Generate the bundled list of rail and light-rail stations from the MOT GTFS.

    python tools/gen_rail_stations.py                      (downloads the feed, ~200 MB)
    python tools/gen_rail_stations.py israel-gtfs.zip      (uses a feed you already have)

Writes core/src/main/kotlin/il/transit/core/geo/RailStationsData.kt. "Let me off on the
way" uses it for long drives instead of downloading every stop of the corridor from
Transitous (whose map/stops ignores `modes`). Re-run when a station or line opens.

The feed comes from the Ministry of Transport, not Transitous: their policy is "don't
scrape, download the data". Only stops served by rail (route_type 2) or light rail /
metro (0, 1) are kept. Importance = departures in the feed, scaled to the busiest = 1.
"""
from __future__ import annotations

import csv
import io
import math
import pathlib
import sys
import tempfile
import urllib.request
import zipfile
from collections import Counter

FEED_URL = "https://gtfs.mot.gov.il/gtfsfiles/israel-public-transportation.zip"
UA = "IsraelTransitPlanner/0.1 (+https://github.com/EitanPinczowski/israel-transit-planner)"
# Transitous prefixes the MOT feed's stop ids with this; keep ids comparable with plan answers.
STOP_ID_PREFIX = "il-Israel-MOT_"
MODES = {"0": "TRAM", "1": "SUBWAY", "2": "RAIL"}
MERGE_M = 300
OUT = pathlib.Path(__file__).resolve().parent.parent / "core/src/main/kotlin/il/transit/core/geo/RailStationsData.kt"


def rows(z: zipfile.ZipFile, name: str):
    with z.open(name) as f:
        yield from csv.DictReader(io.TextIOWrapper(f, encoding="utf-8-sig"))


def distance_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    dy = (lat2 - lat1) * 111_320
    dx = (lon2 - lon1) * 111_320 * math.cos(math.radians(lat1))
    return math.hypot(dx, dy)


def kotlin_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def generate(feed: pathlib.Path) -> str:
    with zipfile.ZipFile(feed) as z:
        route_mode = {r["route_id"]: MODES[r["route_type"]] for r in rows(z, "routes.txt") if r["route_type"] in MODES}
        trip_mode = {t["trip_id"]: route_mode[t["route_id"]] for t in rows(z, "trips.txt") if t["route_id"] in route_mode}
        departures: Counter[str] = Counter()
        stop_modes: dict[str, set[str]] = {}
        for st in rows(z, "stop_times.txt"):  # the big one: streamed, never loaded whole
            mode = trip_mode.get(st["trip_id"])
            if mode:
                departures[st["stop_id"]] += 1
                stop_modes.setdefault(st["stop_id"], set()).add(mode)
        stops = {s["stop_id"]: s for s in rows(z, "stops.txt") if s["stop_id"] in departures}
    # Light rail has one stop id per platform/direction: merge same-name stops within
    # MERGE_M into one station (busiest id kept, departures summed).
    stations: list[dict] = []
    for stop_id in sorted(stops, key=lambda i: (-departures[i], i)):
        s = stops[stop_id]
        name, lat, lon = s["stop_name"].strip(), float(s["stop_lat"]), float(s["stop_lon"])
        twin = next((t for t in stations if t["name"] == name and distance_m(t["lat"], t["lon"], lat, lon) < MERGE_M), None)
        if twin:
            twin["departures"] += departures[stop_id]
            twin["modes"] |= stop_modes[stop_id]
        else:
            stations.append({"id": stop_id, "name": name, "lat": lat, "lon": lon,
                             "departures": departures[stop_id], "modes": set(stop_modes[stop_id])})
    stations.sort(key=lambda t: (-t["departures"], t["id"]))
    busiest = stations[0]["departures"]
    lines = []
    for t in stations:
        modes = ", ".join(kotlin_string(m) for m in sorted(t["modes"]))
        lines.append(
            f"        Place({kotlin_string(t['name'])}, {t['lat']}, {t['lon']}, "
            f"stopId = {kotlin_string(STOP_ID_PREFIX + t['id'])}, importance = {t['departures'] / busiest:.4f}, "
            f"modes = listOf({modes})),"
        )
    return (
        "package il.transit.core.geo\n\n"
        "import il.transit.core.api.Place\n\n"
        f"// GENERATED by tools/gen_rail_stations.py from {feed.name} — do not edit by hand.\n"
        f"// {len(lines)} stations, busiest first.\n"
        "internal object RailStationsData {\n"
        "    val ALL: List<Place> = listOf(\n" + "\n".join(lines) + "\n    )\n}\n"
    )


def main() -> int:
    if len(sys.argv) > 2:
        print(__doc__)
        return 2
    if len(sys.argv) == 2:
        feed = pathlib.Path(sys.argv[1])
    else:
        feed = pathlib.Path(tempfile.gettempdir()) / "israel-public-transportation.zip"
        print(f"downloading {FEED_URL} …")
        req = urllib.request.Request(FEED_URL, headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=600) as r, open(feed, "wb") as f:
            while chunk := r.read(1 << 20):
                f.write(chunk)
    OUT.write_text(generate(feed), encoding="utf-8")
    print(f"wrote {OUT.relative_to(OUT.parents[8])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
